// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDKFs5VKC_ENTvYuv9FGETdvuGNDhNm0YY',
    appId: '1:819917758683:web:46bdc341d630bfe8c1acfe',
    messagingSenderId: '819917758683',
    projectId: 'fir-momo-app',
    authDomain: 'fir-momo-app.firebaseapp.com',
    storageBucket: 'fir-momo-app.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDfmxPyuw2VZk1v6lm7sY6W5qPBzkBehQ4',
    appId: '1:819917758683:android:1d5c232e0904c2ddc1acfe',
    messagingSenderId: '819917758683',
    projectId: 'fir-momo-app',
    storageBucket: 'fir-momo-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBaAtiE-TnPtT1-tLqOoGIkocG1MDrNz1o',
    appId: '1:819917758683:ios:a78bda26a646b703c1acfe',
    messagingSenderId: '819917758683',
    projectId: 'fir-momo-app',
    storageBucket: 'fir-momo-app.appspot.com',
    iosClientId: '819917758683-e4b319r02f86hkb1bct92eg8ettggffm.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutter20230103MemoApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBaAtiE-TnPtT1-tLqOoGIkocG1MDrNz1o',
    appId: '1:819917758683:ios:a78bda26a646b703c1acfe',
    messagingSenderId: '819917758683',
    projectId: 'fir-momo-app',
    storageBucket: 'fir-momo-app.appspot.com',
    iosClientId: '819917758683-e4b319r02f86hkb1bct92eg8ettggffm.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutter20230103MemoApp',
  );
}
